### ISSUE TITLE
第一階段功能

### ISSUE THREAD

**Issue by abc873693** [abc873693/WTUC-AP#1]
- [x] 登入
- [x] 學期課表
- [x] 學期成績
- [x] 最新消息
- [x] 個人資料
- [x] 學校地圖
- [x] 學校電話
- [x] 行事曆

**Comment by takidog** [comment]
[行事曆 ](https://a001.wzu.edu.tw/category/6952)  
日間/進修是拆開的

[電話列表](https://m.wzu.edu.tw/wenzao/device/compliant/people/group?group=group1&_b=%5B%7B%22t%22%3A%22%5Cu901a%5Cu8a0a%5Cu9304%22%2C%22lt%22%3A%22%5Cu901a%5Cu8a0a%5Cu9304%22%2C%22p%22%3A%22index%22%2C%22a%22%3A%22%22%7D%5D)

[地圖](https://c034.wzu.edu.tw/category/140415)

**Comment by takidog** [comment]
爬蟲實作
- [X]  SSO/AP 登入
- [X]  學期列表
- [X]  學期課表
- [X]  學期成績 
* 學期成績- UI 需要更動，`detail`無法實作，不了解對方平均算法等，
如果要更詳細，可能要轉爬歷史成績頁面去parse

- [x]  最新消息 (沿用高科舊的，可直接上線)
- [x]  個人資料

**Comment by abc873693** [comment]
> 爬蟲實作
> 
> * [x]   SSO/AP 登入
> * [x]   學期列表
> * [x]   學期課表
> * [x]   學期成績
> 
> * 學期成績- UI 需要更動，`detail`無法實作，不了解對方平均算法等，
>   如果要更詳細，可能要轉爬歷史成績頁面去parse
> 
> * [ ]   最新消息 (沿用高科舊的，可直接上線)
> * [x]   個人資料

學期成績 那就是 都留空
最新消息可以先暫時用gist

**Comment by abc873693** [comment]
已完成初步功能
仍有些問題轉至
https://github.com/abc873693/ap_common/issues/27
https://github.com/abc873693/WTUC-AP/issues/3
